In [3]:
import cv2
import numpy as np

In [25]:
## 직선 검출
src = cv2.imread('image/road.jpg', 1)
##src = cv2.resize(src, dsize = (0,0), fx = 0.5, fy = 0.5,interpolation = cv2.INTER_AREA)
dst = src.copy()
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
canny = cv2.Canny(gray, 5000, 1500, apertureSize = 5, L2gradient = True)
lines = cv2.HoughLines(canny, 0.8, np.pi / 180, 150, srn = 100, min_theta = 0, max_theta = np.pi)

for i in lines:
    rho, theta = i[0][0], i[0][1]
    a, b = np.cos(theta), np.sin(theta)
    x0, y0 = a*rho, b*rho
    
    scale = src.shape[0] + src.shape[1]
    
    x1 = int(x0 + scale * -b)
    y1 = int(y0 + scale * a)
    x2 = int(x0 - scale * -b)
    y2 = int(y0 - scale * a)
    
    cv2.line(dst,(x1,y1),(x2,y2),(0,0,255),2)
    cv2.circle(dst,(x0.astype(np.uint16),y0.astype(np.uint16)),3, (255,0,0), 5,cv2.FILLED)
    ## circle 함수는 중앙점을 대입할 때 자료형이 uint16 이여야 함.
    
    
cv2.imshow('canny',canny)   
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
print(lines)

[[[  9.2         2.0943952]]

 [[ -1.2         2.1118484]]

 [[451.6         1.134464 ]]

 [[448.4         1.1519173]]

 [[ 28.4         2.0769417]]

 [[ 14.8         2.0943952]]

 [[447.6         1.134464 ]]

 [[450.80002     1.1519173]]

 [[ 51.600002    2.042035 ]]

 [[ 24.4         2.0769417]]

 [[ 42.          2.0594885]]

 [[450.          1.1170107]]]
